# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingsystem', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='conservation',
            field=models.CharField(default='Regular', max_length=200),
            preserve_default=False,
        ),
    ]
