# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingsystem', '0004_auto_20161130_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='offers',
            field=models.ManyToManyField(to='tradingsystem.Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradingsystem.Ad'),
            preserve_default=False,
        ),
    ]
