# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingsystem', '0005_auto_20161201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
