# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingsystem', '0006_auto_20161201_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='active',
        ),
    ]
