# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradingsystem', '0007_remove_trade_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='emailAdvertiser',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='emailOfferor',
        ),
        migrations.AddField(
            model_name='trade',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_advertiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='offeror',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_offeror', to=settings.AUTH_USER_MODEL),
        ),
    ]
