# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradingsystem', '0008_auto_20161201_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
